---
collections:
  - name: community.vmware
  - name: community.general
    version: ">=9.0.0"
  - name: community.windows
  - name: ibm.power_hmc
  - name: awx.awx
  - name: community.mysql
    version: ">=3.15.0"
